VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Class1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private m_count As Integer

Public Sub IncrementCount()

    m_count = m_count + 1

End Sub

Public Function GetCount() As Integer

    GetCount = m_count

End Function

Private Sub Class_Initialize()

    m_count = 0

End Sub
