Attribute VB_Name = "modFunctions"
Option Explicit

' This is where all the server interaction is.
' Is it recommended you DO NOT edit this file.
' If you do you could screw the plugin and/or server up.

Public Function WarpBot(TheMap As Integer, MapX As Integer, MapY As Integer, MapDirection As Integer)
    Call Codes.MoveBotTo(BotIndex, TheMap, MapX, MapY, MapDirection)
End Function

Public Function SendMapMSG(Message As String)
    Call Codes.SendTheMapMSG(Message, LocalSocket)
End Function

Public Function SendEmoteMSG(Message As String)
    Call Codes.SendTheEmoteMSG(Message, LocalSocket)
End Function

Public Function SendBroadcastMSG(Message As String)
    Call Codes.SendTheBroadcastMSG(Message, LocalSocket)
End Function

Public Function SendPrivateMSG(Person As String, Message As String)
    Call Codes.SendThePrivateMSG(Message, Person, LocalSocket)
End Function

Public Function KickPlayer(Person As String)
    Call Codes.KickThePlayer(Person, BotIndex)
End Function
